version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    volumes:
      - ./uploads:/app/uploads
    environment:
      - OPENAI_API_KEY=yourkey    # Set your actual OpenAI API key
